FROM python:3.11-slim

ENV PYTHONPATH=/app
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY mcp_server/requirements.txt .
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.txt

# Копируем весь корень проекта
COPY . .

ENTRYPOINT ["python", "mcp_server/mcp_server.py"]