import os
import sys
import json
from dotenv import load_dotenv
from pathlib import Path

# Выравниваем пути
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from strands import Agent
from strands.models import BedrockModel

from rich.console import Console
from rich.panel import Panel
from rich.theme import Theme

from mcp_server.mcp_server import DATASET_REGISTRY
from context_builder.context_builder import collect_governance_context
from mcp_server.utils.github_utils import create_remediation_pr

# Импортируем системный промпт из твоего файла system_prompts.py
from prompts.system_prompts import GOVERNANCE_SYSTEM_PROMPT

# Load Environment Variables
load_dotenv()

# Initialize Rich Console
custom_theme = Theme({
    "info": "cyan",
    "warning": "yellow",
    "error": "bold red",
    "success": "bold green",
    "highlight": "magenta",
})
console = Console(theme=custom_theme)

# Initialize AWS Bedrock Model via Strands SDK
bedrock_model = BedrockModel(
    model_id=os.getenv("AWS_BEDROCK_MODEL_ID", "amazon.nova-pro-v1:0"),
    region_name=os.getenv("AWS_REGION", "us-east-1"),
)

def build_sql_remediation_artifact(context_data: dict) -> str:
    """Детерминированно строит SQL-скрипт очистки из реального контекста (без LLM)."""
    anomalies = context_data.get("anomalies", [])
    
    if not anomalies:
        return "-- No critical anomalies detected. Pipelines operating normally.\nSELECT * FROM raw_patients;"

    cleaned_fields = ["patient_id"]
    handled_cols = set()

    for item in anomalies:
        col = item.get("column")
        if not col or col in handled_cols or col == "patient_id":
            continue

        issue = str(item.get("issue_type", "")).lower()
        
        if "negative" in issue or "less than" in issue or "< 0" in issue:
            cleaned_fields.append(f"    CASE WHEN {col} < 0 THEN 0.00 ELSE {col} END AS {col}")
        elif "null" in issue or "missing" in issue:
            cleaned_fields.append(f"    COALESCE({col}, 'UNKNOWN') AS {col}")
        elif "outlier" in issue or "range" in issue:
            cleaned_fields.append(f"    CASE WHEN {col} < 0 OR {col} > 120 THEN NULL ELSE {col} END AS {col}")
        else:
            cleaned_fields.append(f"    {col}")
        
        handled_cols.add(col)

    # Добавляем остальные поля, если их не было в аномалиях
    if "date_of_admission" not in handled_cols:
        cleaned_fields.append("    date_of_admission")

    select_clause = ",\n".join(cleaned_fields)

    sql_code = f"""-- Remediation View: models/cleaned_patients.sql
-- Automatically generated by Albugent v2.0 Artifact Engine

SELECT 
{select_clause}
FROM raw_patients
WHERE billing_amount >= 0 OR billing_amount IS NULL;
"""
    return sql_code

def main():
    console.print(Panel.fit(
        "[bold white]🤖 ALBUGENT 2.0: AUTONOMOUS DATA GOVERNANCE ENGINE[/bold white]\n"
        "[dim]Powered by AWS Strands SDK & Bedrock Nova Pro (CI/CD Mode)[/dim]",
        style="blue"
    ))

    # 1. ДЕТЕРМИНИРОВАННЫЙ СБОР ДАННЫХ
    with console.status("[bold cyan]Gathering Deterministic Governance Context...", spinner="dots"):
        raw_context = collect_governance_context(DATASET_REGISTRY)
        context_json_str = json.dumps(raw_context, indent=2, ensure_ascii=False)
    
    console.print("[info]✅ Governance Context (Profile, Lineage, Risk) fully aggregated.[/info]")

    # =========================================================================
    # 2. ДЕТЕРМИНИРОВАННАЯ ГЕНЕРАЦИЯ АРТЕФАКТОВ
    # =========================================================================
    
    # 1. Сборка SQL-артефакта через Python Engine (0% блокировок AWS Bedrock)
    console.print("\n[bold green]🛠️ Building Deterministic SQL Remediation Artifact...[/bold green]")
    sql_code = build_sql_remediation_artifact(raw_context)

    # 2. Вызов Bedrock ТОЛЬКО для генерации текстового Markdown-отчета
    agent = Agent(
        model=bedrock_model,
        system_prompt=GOVERNANCE_SYSTEM_PROMPT
    )

    pr_body_prompt = (
        "Generate a concise, professional GitHub Pull Request summary in clean Markdown "
        "based on this data audit payload. Include a Table of Quality Variances and "
        "Pipeline Lineage Status (PAUSED / OPERATIONAL). Do NOT write any SQL code:\n\n"
        f"{context_json_str}"
    )

    with console.status("[bold cyan]Generating PR Audit Summary via Bedrock...", spinner="dots"):
        pr_body_raw = str(agent(pr_body_prompt)).strip()

    # Очистка ответа от возможных тройных кавычек markdown
    if "```markdown" in pr_body_raw:
        pr_body = pr_body_raw.split("```markdown")[1].split("```")[0].strip()
    elif "```" in pr_body_raw and not pr_body_raw.startswith("##"):
        pr_body = pr_body_raw.split("```")[1].split("```")[0].strip()
    else:
        pr_body = pr_body_raw

    # 3. Финальная сборка payload
    data_payload = {
        "pr_body": pr_body,
        "remediation_file_path": "models/cleaned_patients.sql",
        "sql_code": sql_code
    }

    console.print("\n[bold green]✅ Governance Artifacts Successfully Constructed![/bold green]")
    console.print(Panel(
        f"[bold font]{data_payload['pr_body']}[/bold font]",
        title="[bold cyan]Generated Audit Summary[/bold cyan]",
        border_style="cyan"
    ))

    # =========================================================================
    # 3. АВТОНОМНОЕ СОЗДАНИЕ DRAFT PR В GITHUB
    # =========================================================================
    repo_name = os.getenv("GITHUB_REPOSITORY", "evaaliya/albugent_v2.0")
    
    console.print("\n[bold yellow]🚀 Dispatching Automated Draft Remediation PR to GitHub...[/bold yellow]")
    
    with console.status("[bold green]Creating Draft Pull Request...", spinner="earth"):
        pr_url = create_remediation_pr(
            repo_name=repo_name,
            pr_title="🚨 [Albugent Draft] Automated Data Cleansing & Circuit Breaker Proposal",
            pr_body_markdown=data_payload["pr_body"],
            remediation_file_path=data_payload["remediation_file_path"],
            remediation_sql_code=data_payload["sql_code"]
        )

    if "http" in pr_url:
        console.print(f"\n[bold green]✅ Draft PR successfully created for Human Review:[/bold green]")
        console.print(f"[bold highlight]{pr_url}[/bold highlight]\n")
    else:
        console.print(f"\n[bold red]❌ Failed to create PR: {pr_url}[/bold red]\n")


if __name__ == "__main__":
    main()