import os
import sys
import json
from dotenv import load_dotenv
from pathlib import Path
from collections import defaultdict

# Выравниваем пути
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from strands import Agent
from strands.models import BedrockModel

from rich.console import Console
from rich.panel import Panel
from rich.theme import Theme

from mcp_server.mcp_server import DATASET_REGISTRY
from context_builder.context_builder import collect_governance_context
from mcp_server.utils.github_utils import create_remediation_pr

# Импортируем системный промпт из твоего файла system_prompts.py
from prompts.system_prompts import GOVERNANCE_SYSTEM_PROMPT

# Load Environment Variables
load_dotenv()

# Initialize Rich Console
custom_theme = Theme({
    "info": "cyan",
    "warning": "yellow",
    "error": "bold red",
    "success": "bold green",
    "highlight": "magenta",
})
console = Console(theme=custom_theme)

# Initialize AWS Bedrock Model via Strands SDK
bedrock_model = BedrockModel(
    model_id=os.getenv("AWS_BEDROCK_MODEL_ID", "amazon.nova-pro-v1:0"),
    region_name=os.getenv("AWS_REGION", "us-east-1"),
)

def build_sql_remediation_artifact(context_data: dict) -> str:
    """Детерминированно строит SQL-скрипт очистки из реального контекста (без LLM)."""
    anomalies = context_data.get("anomalies", [])
    
    if not anomalies:
        return "-- No critical anomalies detected. Pipelines operating normally.\nSELECT * FROM raw_patients;"

    cleaned_fields = ["patient_id"]
    handled_cols = set()

    for item in anomalies:
        col = item.get("column")
        if not col or col in handled_cols or col == "patient_id":
            continue

        issue = str(item.get("issue_type", "")).lower()
        
        if "negative" in issue or "less than" in issue or "< 0" in issue:
            cleaned_fields.append(f"    CASE WHEN {col} < 0 THEN 0.00 ELSE {col} END AS {col}")
        elif "null" in issue or "missing" in issue:
            cleaned_fields.append(f"    COALESCE({col}, 'UNKNOWN') AS {col}")
        elif "outlier" in issue or "range" in issue:
            cleaned_fields.append(f"    CASE WHEN {col} < 0 OR {col} > 120 THEN NULL ELSE {col} END AS {col}")
        else:
            cleaned_fields.append(f"    {col}")
        
        handled_cols.add(col)

    # Добавляем остальные поля, если их не было в аномалиях
    if "date_of_admission" not in handled_cols:
        cleaned_fields.append("    date_of_admission")

    select_clause = ",\n".join(cleaned_fields)

    sql_code = f"""-- Remediation View: models/cleaned_patients.sql
-- Automatically generated by Albugent v2.0 Artifact Engine

SELECT 
{select_clause}
FROM raw_patients
WHERE billing_amount >= 0 OR billing_amount IS NULL;
"""
    return sql_code


def summarize_anomalies_for_prompt(raw_context):
    """
    Группирует сырые аномалии по таблицам и типам, чтобы не превысить лимит токенов,
    но сохранить полную статистику (сколько именно отрицательных чисел/null'ов найдено).
    """
    summary = defaultdict(lambda: defaultdict(int))
    
    # Предполагаем, что raw_context содержит список аномалий или словарь с ними
    # Подстройте под структуру вашего raw_context, если ключи отличаются
    anomalies_list = raw_context.get("anomalies", raw_context) if isinstance(raw_context, dict) else raw_context
    
    if isinstance(anomalies_list, list):
        for item in anomalies_list:
            dataset = item.get("dataset", item.get("urn", "unknown_dataset"))
            column = item.get("column", "unknown_column")
            entry_type = item.get("entry_type", item.get("type", "Quality Variance"))
            
            key = (dataset, column, entry_type)
            summary[dataset][(column, entry_type)] += 1

    # Формируем компактный и читаемый текст для промпта
    report_lines = []
    for dataset, cols in summary.items():
        report_lines.append(f"Dataset: {dataset}")
        for (col, err_type), count in cols.items():
            report_lines.append(f"  - Column '{col}': {count} occurrences of '{err_type}'")
            
    return "\n".join(report_lines)

def main():
    console.print(Panel.fit(
        "[bold white]🤖 ALBUGENT 2.0: AUTONOMOUS DATA GOVERNANCE ENGINE[/bold white]\n"
        "[dim]Powered by AWS Strands SDK & Bedrock Nova Pro (CI/CD Mode)[/dim]",
        style="blue"
    ))

    # 1. ДЕТЕРМИНИРОВАННЫЙ СБОР ДАННЫХ
    with console.status("[bold cyan]Gathering Deterministic Governance Context...", spinner="dots"):
        raw_context = collect_governance_context(DATASET_REGISTRY)
        context_json_str = json.dumps(raw_context, indent=2, ensure_ascii=False)
    
    console.print("[info]✅ Governance Context (Profile, Lineage, Risk) fully aggregated.[/info]")

    # =========================================================================
    # 2. ДЕТЕРМИНИРОВАННАЯ ГЕНЕРАЦИЯ АРТЕФАКТОВ
    # =========================================================================
    
    # 1. Генерируем SQL детерминированно в Python
    console.print("\n[bold green]🛠️ Building Deterministic SQL Remediation Artifact...[/bold green]")
    sql_code = build_sql_remediation_artifact(raw_context)

    # 2. Агрегируем аномалии для промпта
    aggregated_summary = summarize_anomalies_for_prompt(raw_context)

    # 3. Вызываем Bedrock для генерации отчета
    agent = Agent(
        model=bedrock_model,
        system_prompt=GOVERNANCE_SYSTEM_PROMPT
    )

    pr_body_prompt = (
        "Generate a concise, professional GitHub Pull Request summary in clean Markdown "
        "based on this aggregated data audit summary. Include a structured Table of Quality Variances "
        "showing exact counts per column and error type, and Pipeline Lineage Status. "
        "Strictly output ONLY Markdown text. Do NOT include SQL code blocks in this description:\n\n"
        f"{aggregated_summary}"
    )

    with console.status("[bold cyan]Generating PR Audit Summary via Bedrock...", spinner="dots"):
        pr_body_raw = str(agent(pr_body_prompt)).strip()

    # Очищаем возможные обертки markdown
    pr_body = pr_body_raw
    if "```markdown" in pr_body:
        pr_body = pr_body.split("```markdown")[1].split("```")[0].strip()
    elif "```" in pr_body:
        pr_body = pr_body.split("```")[1].split("```")[0].strip()

    # Заменяем literal \n на реальные переносы строк, если они экранированы
    pr_body = pr_body.replace("\\n", "\n")

    console.print("\n[bold green]✅ Governance Artifacts Successfully Constructed![/bold green]")

    # 4. АВТОНОМНОЕ СОЗДАНИЕ DRAFT PR В GITHUB
    repo_name = os.getenv("GITHUB_REPOSITORY", "evaaliya/albugent_v2.0")
    
    console.print("\n[bold yellow]🚀 Dispatching Automated Draft Remediation PR to GitHub...[/bold yellow]")
    
    with console.status("[bold green]Creating Draft Pull Request...", spinner="earth"):
        pr_url = create_remediation_pr(
            repo_name=repo_name,
            pr_title="🚨 [Albugent Draft] Automated Data Cleansing & Circuit Breaker Proposal",
            pr_body_markdown=pr_body,                  # Текст отчета с таблицей
            remediation_file_path="models/cleaned_patients.sql",
            remediation_sql_code=sql_code              # Тот самый сгенерированный SQL-код
        )

    if "http" in pr_url:
        console.print(f"\n[bold green]✅ Draft PR successfully created for Human Review:[/bold green]")
        console.print(f"[bold highlight]{pr_url}[/bold highlight]\n")
    else:
        console.print(f"\n[bold red]❌ Failed to create PR: {pr_url}[/bold red]\n")

if __name__ == "__main__":
    main()